clc;
clear all;
close all;
n=0:1:100;
M=3;
x=cos(pi*n/3);
x_up=zeros(1,length(x)*M);
x_up(1:M:end)=x;
h=fir1(101,1/M,hamming(102));
x_lpf=conv(x_up,h);
x_interp=x_lpf(51:end-50);
stem(x);
figure;
stem(x_up);
figure;
stem(x_interp);
X_f=fftshift(fft(x,100));
Xup_f=fftshift(fft(x_up,100));
Xinterp_f=fftshift(fft(x_interp,100));
xaxis=linspace(-1,1,100);
figure;
plot(xaxis,abs(X_f));
figure;
plot(xaxis,abs(Xup_f));
figure;
plot(xaxis,abs(Xinterp_f));
figure;